package com.lubanresearch.lubanmall.commentservice.infrastructure.persistence.db.mapper;

import com.lubanresearch.lubanmall.commentservice.domain.Comment;
import com.lubanresearch.lubanmall.commentservice.infrastructure.persistence.db.query.condition.CommentQueryCondition;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommentMapper {
    long countByExample(CommentQueryCondition example);

    int deleteByExample(CommentQueryCondition example);

    int deleteByPrimaryKey(Long id);

    int insert(Comment record);

    int insertSelective(Comment record);

    List<Comment> selectByExample(CommentQueryCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<Comment> selectByExampleSelective(@Param("example") CommentQueryCondition example, @Param("selective") Comment.Column ... selective);

    Comment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Comment selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") Comment.Column ... selective);

    int updateByExampleSelective(@Param("record") Comment record, @Param("example") CommentQueryCondition example);

    int updateByExample(@Param("record") Comment record, @Param("example") CommentQueryCondition example);

    int updateByPrimaryKeySelective(Comment record);

    int updateByPrimaryKey(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsert(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertSelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExample(@Param("record") Comment record, @Param("example") CommentQueryCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExampleSelective(@Param("record") Comment record, @Param("example") CommentQueryCondition example);
}