package com.lubanresearch.lubanmall.catagoryservice.infrastructure.persistence.db.mapper;

import com.lubanresearch.lubanmall.catagoryservice.domain.Category;
import com.lubanresearch.lubanmall.catagoryservice.infrastructure.persistence.db.query.condition.CategoryQueryCondition;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CategoryMapper {
    long countByExample(CategoryQueryCondition example);

    int deleteByExample(CategoryQueryCondition example);

    int deleteByPrimaryKey(Long id);

    int insert(Category record);

    int insertSelective(Category record);

    List<Category> selectByExample(CategoryQueryCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<Category> selectByExampleSelective(@Param("example") CategoryQueryCondition example, @Param("selective") Category.Column ... selective);

    Category selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Category selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") Category.Column ... selective);

    int updateByExampleSelective(@Param("record") Category record, @Param("example") CategoryQueryCondition example);

    int updateByExample(@Param("record") Category record, @Param("example") CategoryQueryCondition example);

    int updateByPrimaryKeySelective(Category record);

    int updateByPrimaryKey(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsert(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertSelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExample(@Param("record") Category record, @Param("example") CategoryQueryCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExampleSelective(@Param("record") Category record, @Param("example") CategoryQueryCondition example);
}