package com.lubanresearch.lubanmall.merchantservice.infrastructure.persistence.db.mapper;

import com.lubanresearch.lubanmall.merchantservice.domain.Shop;
import com.lubanresearch.lubanmall.merchantservice.infrastructure.persistence.db.query.condition.ShopQueryCondition;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopMapper {
    long countByExample(ShopQueryCondition example);

    int deleteByExample(ShopQueryCondition example);

    int deleteByPrimaryKey(Long id);

    int insert(Shop record);

    int insertSelective(Shop record);

    List<Shop> selectByExampleWithBLOBs(ShopQueryCondition example);

    List<Shop> selectByExample(ShopQueryCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_shop
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<Shop> selectByExampleSelective(@Param("example") ShopQueryCondition example, @Param("selective") Shop.Column ... selective);

    Shop selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_shop
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Shop selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") Shop.Column ... selective);

    int updateByExampleSelective(@Param("record") Shop record, @Param("example") ShopQueryCondition example);

    int updateByExampleWithBLOBs(@Param("record") Shop record, @Param("example") ShopQueryCondition example);

    int updateByExample(@Param("record") Shop record, @Param("example") ShopQueryCondition example);

    int updateByPrimaryKeySelective(Shop record);

    int updateByPrimaryKeyWithBLOBs(Shop record);

    int updateByPrimaryKey(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_shop
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsert(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_shop
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertWithBLOBs(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_shop
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertSelective(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_shop
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExample(@Param("record") Shop record, @Param("example") ShopQueryCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_shop
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExampleWithBLOBs(@Param("record") Shop record, @Param("example") ShopQueryCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_shop
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExampleSelective(@Param("record") Shop record, @Param("example") ShopQueryCondition example);
}