package com.lubanresearch.lubanmall.demoservice.infrastructure.persistence.db;

import com.lubanresearch.lubanmall.demoservice.domain.Demo;
import com.lubanresearch.lubanmall.demoservice.domain.query.condition.DemoQueryCondition;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DemoMapper {
    long countByExample(DemoQueryCondition example);

    int deleteByExample(DemoQueryCondition example);

    int deleteByPrimaryKey(Long id);

    int insert(Demo record);

    int insertSelective(Demo record);

    List<Demo> selectByExample(DemoQueryCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_demo
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<Demo> selectByExampleSelective(@Param("example") DemoQueryCondition example, @Param("selective") Demo.Column ... selective);

    Demo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_demo
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Demo selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") Demo.Column ... selective);

    int updateByExampleSelective(@Param("record") Demo record, @Param("example") DemoQueryCondition example);

    int updateByExample(@Param("record") Demo record, @Param("example") DemoQueryCondition example);

    int updateByPrimaryKeySelective(Demo record);

    int updateByPrimaryKey(Demo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_demo
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsert(Demo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_demo
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertSelective(Demo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_demo
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExample(@Param("record") Demo record, @Param("example") DemoQueryCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_demo
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExampleSelective(@Param("record") Demo record, @Param("example") DemoQueryCondition example);
}