package com.lubanresearch.lubanmall.cart.infrastructure.persistence.db.mapper;

import com.lubanresearch.lubanmall.cart.infrastructure.persistence.db.entity.CartEntity;
import com.lubanresearch.lubanmall.cart.infrastructure.persistence.db.query.condition.CartEntityQueryCondition;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CartEntityMapper {
    long countByExample(CartEntityQueryCondition example);

    int deleteByExample(CartEntityQueryCondition example);

    int deleteByPrimaryKey(Long id);

    int insert(CartEntity record);

    int insertSelective(CartEntity record);

    List<CartEntity> selectByExample(CartEntityQueryCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_cart
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<CartEntity> selectByExampleSelective(@Param("example") CartEntityQueryCondition example, @Param("selective") CartEntity.Column ... selective);

    CartEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_cart
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CartEntity selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") CartEntity.Column ... selective);

    int updateByExampleSelective(@Param("record") CartEntity record, @Param("example") CartEntityQueryCondition example);

    int updateByExample(@Param("record") CartEntity record, @Param("example") CartEntityQueryCondition example);

    int updateByPrimaryKeySelective(CartEntity record);

    int updateByPrimaryKey(CartEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_cart
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsert(CartEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_cart
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertSelective(CartEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_cart
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExample(@Param("record") CartEntity record, @Param("example") CartEntityQueryCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_cart
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExampleSelective(@Param("record") CartEntity record, @Param("example") CartEntityQueryCondition example);
}