package com.lubanresearch.lubanmall.cart.infrastructure.persistence.db.mapper;

import com.lubanresearch.lubanmall.cart.infrastructure.persistence.db.entity.CartItemEntity;
import com.lubanresearch.lubanmall.cart.infrastructure.persistence.db.query.condition.CartItemEntityQueryCondition;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CartItemEntityMapper {
    long countByExample(CartItemEntityQueryCondition example);

    int deleteByExample(CartItemEntityQueryCondition example);

    int deleteByPrimaryKey(Long id);

    int insert(CartItemEntity record);

    int insertSelective(CartItemEntity record);

    List<CartItemEntity> selectByExample(CartItemEntityQueryCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_cart_item
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<CartItemEntity> selectByExampleSelective(@Param("example") CartItemEntityQueryCondition example, @Param("selective") CartItemEntity.Column ... selective);

    CartItemEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_cart_item
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CartItemEntity selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") CartItemEntity.Column ... selective);

    int updateByExampleSelective(@Param("record") CartItemEntity record, @Param("example") CartItemEntityQueryCondition example);

    int updateByExample(@Param("record") CartItemEntity record, @Param("example") CartItemEntityQueryCondition example);

    int updateByPrimaryKeySelective(CartItemEntity record);

    int updateByPrimaryKey(CartItemEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_cart_item
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsert(CartItemEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_cart_item
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertSelective(CartItemEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_cart_item
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExample(@Param("record") CartItemEntity record, @Param("example") CartItemEntityQueryCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_cart_item
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExampleSelective(@Param("record") CartItemEntity record, @Param("example") CartItemEntityQueryCondition example);
}