package com.lubanresearch.lubanmall.orderservice.infrastructure.persistence.db;

import com.lubanresearch.lubanmall.orderservice.domain.bean.OrderItem;
import com.lubanresearch.lubanmall.orderservice.domain.query.condition.OrderItemQueryCondition;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrderItemMapper {
    long countByExample(OrderItemQueryCondition example);

    int deleteByExample(OrderItemQueryCondition example);

    int deleteByPrimaryKey(Long id);

    int insert(OrderItem record);

    int insertSelective(OrderItem record);

    List<OrderItem> selectByExample(OrderItemQueryCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_order_item
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<OrderItem> selectByExampleSelective(@Param("example") OrderItemQueryCondition example, @Param("selective") OrderItem.Column ... selective);

    OrderItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_order_item
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    OrderItem selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") OrderItem.Column ... selective);

    int updateByExampleSelective(@Param("record") OrderItem record, @Param("example") OrderItemQueryCondition example);

    int updateByExample(@Param("record") OrderItem record, @Param("example") OrderItemQueryCondition example);

    int updateByPrimaryKeySelective(OrderItem record);

    int updateByPrimaryKey(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_order_item
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsert(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_order_item
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertSelective(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_order_item
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExample(@Param("record") OrderItem record, @Param("example") OrderItemQueryCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_order_item
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExampleSelective(@Param("record") OrderItem record, @Param("example") OrderItemQueryCondition example);
}